### ISSUE TITLE
whitenoise fix

### ISSUE THREAD

**Issue by poiedk** [app-generator/django-tabler#1]
The WhiteNoise middleware should be placed directly after the Django SecurityMiddleware (if you are using it) and before all other middleware

```
MIDDLEWARE = [
  'django.middleware.security.SecurityMiddleware',
  'whitenoise.middleware.WhiteNoiseMiddleware',
  # ...
]
```

**Comment by app-generator** [comment]
Thanks for your contribution @poiedk. 

Issue patched in [commit](https://github.com/app-generator/django-dashboard-tabler/commit/d7b0bf57faece7ed0c31baabfe438192bd8586b7).

Patch also ported to master templates used as a reference for all future Django Apps & Dashboards generated by AppSeed.
- [Django Boilerplate](https://github.com/app-generator/boilerplate-code-django)
- [Django Dashboard Boilerplate](https://github.com/app-generator/boilerplate-code-django-dashboard)

Closing the issue.  

P.S. Items 
- In case you will make a purchase from the AppSeed platform, please mention this contribution to get an instant discount.
- Feel free to join the community on [Discord](https://discord.gg/fZC6hup)
