### ISSUE TITLE
Password Reset and Profile image change not working

### ISSUE THREAD

**Issue by 6abc** [app-generator/django-tabler#4]
Password Reset not working from url : http://10.0.0.106:8000/settings/#
Set new password[BUTTON] not working

Profile Image change/Delete avatar not working from url : http://10.0.0.106:8000/settings/#

**Comment by app-generator** [comment]
Hello @6abc 

Some of the links come from the UI Kit and might not work. 
The functional `change password` route can be found in the navigation bar (user menu)

![image](https://github.com/app-generator/django-tabler/assets/51070104/554410ce-6923-489b-8f4e-6ca5c0057463)

Regarding the **profile page**, the feature is not yet provided. 

Let us know if you need further assistance. 
https://appseed.us/support/
